<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Comments Administration'] = 'Kommentare-Administration';
$xarML_PHPBackend_entries['Yes'] = 'Ja';
$xarML_PHPBackend_entries['Overview'] = 'Überblick';
$xarML_PHPBackend_entries['What is it?'] = 'Wozu dient es?';
$xarML_PHPBackend_entries['Comments is a Xaraya Utility Module.'] = 'Das Kommentare-Modul ist ein Xaraya-Dienstprogramm.';
$xarML_PHPBackend_entries['It is currently responsible for accomplishing these tasks:'] = 'Es ist aktuell für die Erfüllung folgender Aufgaben zuständig:';
$xarML_PHPBackend_entries['How to use it?'] = 'Wie setzt man es ein?';
$xarML_PHPBackend_entries['Simply enable the comments hook to any content module, and on the display pages, comments will be available to be used.'] = 'Einfach den Kommentar-Hook bei jedem Inhalts-Modul zulassen, dann steht auf den angezeigten Seiten das Kommentar-Modul zum Gebrauch bereit.';
$xarML_PHPBackend_entries['Included Blocks'] = 'Dazugehörige Blöcke';
$xarML_PHPBackend_entries['The Latest Comment block provides a listing of the most
recent comments made on your site. The number of comments, date of
comment, comments from which modules, comment author and other configuration
variables can be set.'] = 'Der letzte-Kommentare-Block erstellt eine Liste der letzten Kommentare auf Ihrer Website. Die Anzahl der Kommentare, das Datum des Kommentars, innerhalb welches Moduls ein Kommentar erfolgte, der Autor des Kommentars und andere Konfigurationsvariablen können festgesetzt werden.';
$xarML_PHPBackend_entries['Included Hooks'] = 'Dazugehörige Hooks';
$xarML_PHPBackend_entries['Comments provide a display hook for modules to use as needed.'] = 'Das Kommentar-Modul stellt im Bedarfsfall einen Darstellungs-Hook für alle Module zur Verfügung.';
$xarML_PHPBackend_entries['Modify Configuration'] = 'Einstellungen';
$xarML_PHPBackend_entries['Submit'] = 'Speichern';
$xarML_PHPBackend_entries['Comments Module Statistics'] = 'Nutzungsstatistik anzeigen';
$xarML_PHPBackend_entries['Delete'] = 'Löschen';
$xarML_PHPBackend_entries['Comments'] = 'Kommentare';
$xarML_PHPBackend_entries['Delete Comment'] = 'Kommentar löschen';
$xarML_PHPBackend_entries['Confirm Comment Deletion'] = 'Kommentarlöschung bestätigen';
$xarML_PHPBackend_entries['Confirm deletion of this comment'] = 'Löschung dieses Kommentars bestätigen';
$xarML_PHPBackend_entries['Are you sure you want to delete this comment?'] = 'Diesen Kommentar wirklich löschen?';
$xarML_PHPBackend_entries['Attach child comments to parent'] = 'Kommentarerwiderungen an den Ursprungskommentar anfügen';
$xarML_PHPBackend_entries['Delete this comment and all children'] = 'Diesen Kommentar mitsamt aller Erwiderungen löschen';
$xarML_PHPBackend_entries['Return to'] = 'Zurück nach';
$xarML_PHPBackend_entries['Title'] = 'Titel';
$xarML_PHPBackend_entries['Author'] = 'Autor';
$xarML_PHPBackend_entries['Default Rendering Style'] = 'Standard-Darstellungsstil';
$xarML_PHPBackend_entries['Nested'] = 'Geschachtelt';
$xarML_PHPBackend_entries['Flat'] = 'Flach';
$xarML_PHPBackend_entries['Threaded'] = 'Gestaffelt';
$xarML_PHPBackend_entries['No Comments'] = 'Keine Kommentare';
$xarML_PHPBackend_entries['Default Sorting Mode'] = 'Standard-Sortierweise';
$xarML_PHPBackend_entries['Date'] = 'Datum';
$xarML_PHPBackend_entries['Thread'] = 'Thema';
$xarML_PHPBackend_entries['Default Sorting Order'] = 'Standard-Sortierreihenfolge';
$xarML_PHPBackend_entries['Ascending'] = 'Ansteigend';
$xarML_PHPBackend_entries['Descending'] = 'Absteigend';
$xarML_PHPBackend_entries['in'] = 'in';
$xarML_PHPBackend_entries['by'] = 'von';
$xarML_PHPBackend_entries['on'] = 'am';
$xarML_PHPBackend_entries['There are no comments'] = 'Es gibt keine Kommentare';
$xarML_PHPBackend_entries['Refresh'] = 'Erneut laden';
$xarML_PHPBackend_entries['All'] = 'Alle';
$xarML_PHPBackend_entries['type #(1)'] = 'Typ #(1)';
$xarML_PHPBackend_entries['Unable to load #(1) #(2)'] = 'Kann #(1) #(2) nicht laden';
$xarML_PHPBackend_entries['Missing [#(1)] field on new #(2)'] = 'Fehlendes [#(1)] Feld am neuen #(2)';
$xarML_PHPBackend_entries['Invalid #(1) for #(2) function #(3)() in module #(4)'] = 'Ungültiges #(1) für #(2) Funktion #(3)() in Modul #(4)';
$xarML_PHPBackend_entries['Missing or Invalid parameter \'cid\'!!'] = 'Fehlender oder ungültiger Parameter "cid"!';
$xarML_PHPBackend_entries['Missing #(1) for #(2) function #(3)() in module #(4)'] = 'Fehlendes #(1) für #(2)-Funktion #(3)() in Modul #(4)';
$xarML_PHPBackend_entries['Missing or Invalid parameter \'modid\'!!'] = 'Ungültiger oder fehlender Parameter "modid"!';
$xarML_PHPBackend_entries['Missing or Invalid parameter \'objectid\'!!'] = 'Ungültiger oder fehlender Parameter "objectid"!';
$xarML_PHPBackend_entries['Missing or Invalid parameter \'startpoint\'!!'] = 'Fehlender oder ungültiger Parameter "startpoint"!!';
$xarML_PHPBackend_entries['Invalid #(1) [#(2)] for #(3) function #(4)() in module #(5)'] = 'Ungültiges #(1) [#(2)] für #(3) Funktion #(4)() in Modul #(5)';
$xarML_PHPBackend_entries['Invalid #(1)'] = 'Ungültig: #(1)';
$xarML_PHPBackend_entries['Unable to create depth by pid'] = 'Kann keine Tiefe nach pid anlegen';
$xarML_PHPBackend_entries['View Statistics'] = 'Statistik anzeigen';
$xarML_PHPBackend_entries['Invalid or Missing Parameter \'modid\''] = 'Ungültiger oder fehlender Parameter "modid"';
$xarML_PHPBackend_entries['Field #(1) (#(2)) is missing.'] = 'Feld #(1) (#(2)) fehlt.';
$xarML_PHPBackend_entries['unknown property'] = 'unbekannte Eigenschaft';
$xarML_PHPBackend_entries['This property is unknown...'] = 'Diese Eigenschaft ist unbekannt...';
$xarML_PHPBackend_entries['View Changes'] = 'Änderungen anzeigen';
$xarML_PHPBackend_entries['View changes'] = 'Änderungen anzeigen';
$xarML_PHPBackend_entries['Posted by:'] = 'Verfasst von:';
$xarML_PHPBackend_entries['Permalink'] = 'Permalink';
?>