<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Blocks Administration'] = 'Blöcke-Administration';
$xarML_PHPBackend_entries['Name:'] = 'Name:';
$xarML_PHPBackend_entries['Members:'] = 'Blockmitglieder:';
$xarML_PHPBackend_entries['none'] = 'keine vorhanden';
$xarML_PHPBackend_entries['Cancel'] = 'Abbrechen';
$xarML_PHPBackend_entries['Title:'] = 'Titel:';
$xarML_PHPBackend_entries['Overview'] = 'Überblick';
$xarML_PHPBackend_entries['Block Types'] = 'Blocktypen';
$xarML_PHPBackend_entries['Enter the name of the group. This value is used in your theme template to call the block group.'] = 'Dieser Name wird im Themen-Template zum Aufruf der Blockgruppe verwandt.';
$xarML_PHPBackend_entries['If you wish to override the default template you may do so by entering a template name. Otherwise the default.xt template will be used.'] = 'Soll das Standard-Template überschrieben werden, kann dies durch Eingabe eines Template-Namens erfolgen. Anderenfalls wird das default.xt-Template verwendet.';
$xarML_PHPBackend_entries['Default Template (optional):'] = 'Standard-Template (optional):';
$xarML_PHPBackend_entries['Instance Parameters'] = 'Eigenschaften der Blockinstanz';
$xarML_PHPBackend_entries['Block Type:'] = 'Blocktyp (Name):';
$xarML_PHPBackend_entries['Default State:'] = 'Standardstatus:';
$xarML_PHPBackend_entries['Hidden'] = 'Verborgen';
$xarML_PHPBackend_entries['Maximized'] = 'Maximiert';
$xarML_PHPBackend_entries['Instance Template (optional):'] = 'Blockinstanz-Vorlagen (optional):';
$xarML_PHPBackend_entries['Update'] = 'Speichern';
$xarML_PHPBackend_entries['Add Group'] = 'Blockgruppe hinzufügen';
$xarML_PHPBackend_entries['Add Instance'] = 'Blockinstanz hinzufügen';
$xarML_PHPBackend_entries['Minimized'] = 'Minimiert';
$xarML_PHPBackend_entries['Create Instance'] = 'Blockinstanz anlegen';
$xarML_PHPBackend_entries['Template'] = 'Template';
$xarML_PHPBackend_entries['default'] = 'Standard';
$xarML_PHPBackend_entries['Edit'] = 'Bearb.';
$xarML_PHPBackend_entries['Delete'] = 'Löschen';
$xarML_PHPBackend_entries['Refresh'] = 'Neu laden';
$xarML_PHPBackend_entries['View Block Type'] = 'Blocktyp anzeigen';
$xarML_PHPBackend_entries['Name'] = 'Name';
$xarML_PHPBackend_entries['View Block Types'] = 'Blocktypen&nbsp;anzeigen';
$xarML_PHPBackend_entries['Module'] = 'Modul';
$xarML_PHPBackend_entries['Type'] = 'Typ';
$xarML_PHPBackend_entries['Actions'] = 'Aktionen';
$xarML_PHPBackend_entries['Add Block Type'] = 'Blocktyp hinzufügen';
$xarML_PHPBackend_entries['Block group name "#(1)" already exists'] = 'Name der Blockgruppe "#(1)" existiert bereits';
$xarML_PHPBackend_entries['Block name "#(1)" already exists'] = 'Blockname "#(1)" existiert bereits';
$xarML_PHPBackend_entries['Invalid parameter'] = 'Ungültiger Parameter';
$xarML_PHPBackend_entries['Modify Config'] = 'Einstellungen';
$xarML_PHPBackend_entries['Invalid parameter: missing module or type'] = 'Ungültiger Parameter: Fehlendes Modul oder fehlender Typ';
$xarML_PHPBackend_entries['Block Groups'] = 'Blockgruppen';
$xarML_PHPBackend_entries['Groups'] = 'Gruppen';
$xarML_PHPBackend_entries['Status'] = 'Status';
$xarML_PHPBackend_entries['View block type details'] = 'Blocktyp-Details anzeigen';
?>