<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Invalid Parameter Count'] = 'Ungültige Parameter-Anzahl';
$xarML_PHPBackend_entries['View Links'] = 'Autolinks';
$xarML_PHPBackend_entries['View Types'] = 'Autolink-Typen';
$xarML_PHPBackend_entries['Add Type'] = 'Neuer Typ';
$xarML_PHPBackend_entries['Modify Config'] = 'Einstellungen';
$xarML_PHPBackend_entries['Utilities'] = 'Hilfsmittel';
$xarML_PHPBackend_entries['Invalid parameter count'] = 'Ungültige Parameter-Anzahl';
$xarML_PHPBackend_entries['No such link type present: #(1)'] = 'Dieser Autolink-Typ ist nicht vorhanden: #(1)';
$xarML_PHPBackend_entries['Autolinks Administration'] = 'Autolinks-Administration';
$xarML_PHPBackend_entries['Cancel'] = 'Abbrechen';
$xarML_PHPBackend_entries['Overview'] = 'Überblick';
$xarML_PHPBackend_entries['View Autolinks'] = 'Autolinks anzeigen';
$xarML_PHPBackend_entries['Edit autolink type'] = 'Autolink-Typ bearbeiten';
$xarML_PHPBackend_entries['Type'] = 'Typ';
$xarML_PHPBackend_entries['Move'] = 'Verschieben';
$xarML_PHPBackend_entries['Name'] = 'Name';
$xarML_PHPBackend_entries['Matching Key'] = 'Schlüsselwort';
$xarML_PHPBackend_entries['Title'] = 'Titel';
$xarML_PHPBackend_entries['URL'] = 'URL';
$xarML_PHPBackend_entries['Comment'] = 'Kommentar';
$xarML_PHPBackend_entries['Configuration of Hooked Modules'] = 'Konfiguration von verbundenen (hooked) Modulen';
$xarML_PHPBackend_entries['Create'] = 'Erstellen';
$xarML_PHPBackend_entries['Add'] = 'Neuer';
$xarML_PHPBackend_entries['Autolink Type'] = 'Autolink-Typ';
$xarML_PHPBackend_entries['Options'] = 'Optionen';
$xarML_PHPBackend_entries['Edit'] = 'Bearbeiten';
$xarML_PHPBackend_entries['Delete'] = 'Löschen';
$xarML_PHPBackend_entries['View Autolink Types'] = 'Autolink-Typen anzeigen';
$xarML_PHPBackend_entries['Template Name'] = 'Template-Name';
$xarML_PHPBackend_entries['name'] = 'Name';
$xarML_PHPBackend_entries['Execute Template Dynamically'] = 'Dynamisch ausführen';
$xarML_PHPBackend_entries['Description'] = 'Beschreibung';
$xarML_PHPBackend_entries['External link icon'] = 'Externer Link-Icon';
$xarML_PHPBackend_entries['Import and Export Utilities'] = 'Hilfmittel';
$xarML_PHPBackend_entries['Export Autolinks'] = 'Autolinks exportieren';
?>