<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Official Icon'] = 'Icône officiel';
$xarML_PHPBackend_entries['Overview'] = 'Aperçu';
$xarML_PHPBackend_entries['What is it?'] = 'Quest-ce que c\'est?';
$xarML_PHPBackend_entries['The Themes module manages the themes available on your Xaraya installation, which in turn define the site\'s display and look-and-feel. It also provides performance and development options for administrators and theme developers. The Themes module is a core module within Xaraya and cannot be removed.'] = 'Le module des thèmes gèrent les thèmes disponibles sur votre installation de Xaraya, qui en retour défini l\'affichage du site et son apparance. Il fournit aussi des options de performance et de développement pour les administrateurs et les développeurs de thème. Le module des thèmes est un module du noyau dans Xaraya et ne peut être supprimer.';
$xarML_PHPBackend_entries['Detail information on this module can be found'] = 'De l\'information détaillée sur ce module peut être trouvée';
$xarML_PHPBackend_entries['Concepts'] = 'Concepts';
$xarML_PHPBackend_entries['Themes in Xaraya control the look and feel of a site. Among the available themes one, called the default theme, is displayed to users (registered and unregistered) by default. If theme switching is allowed, then a user can change his/her profile to have any other of the site\'s active themes be displayed instead.'] = 'Les thèmes dans Xaraya contrôle l\'apparence du site.';
$xarML_PHPBackend_entries['Themes are made up mainly of BlockLayout templates, which fall into two groups:'] = 'Les thèmes sont principalement fait de mosèles de diposition de bloc, qui tombe dans deux groupes:';
$xarML_PHPBackend_entries['Pages:'] = 'Pages:';
$xarML_PHPBackend_entries['are templates found in the theme\'s'] = 'sont les modèles trouvés dans le thème';
$xarML_PHPBackend_entries['pages'] = 'pages';
$xarML_PHPBackend_entries['directory that control the layout of te site\'s page displays. They form the grid which defines where menus, login boxes etc. (generated by blocks), and page content (generated by modules) appear visually. A theme can have as many page templates (each correesponding to a different page layout) as needed.'] = 'registre qui contrôle la disposition de l\'affichages des pages du site. Ils forment la grille qui définie où les menus, les oîtes de déconnexion etc. (généré par des blocs) et le contenu de la page (généré par les modules) apparaît visuellement. Un thème peut avoir autant de modèles de page (chacune correspondant à une diposition de page différente) au besoin';
$xarML_PHPBackend_entries['Overrides:'] = 'Remplace (écrire par-dessus)';
$xarML_PHPBackend_entries['are templates that display.the content of blocks and modules. They override native default templates already present in the respective blocks or modules. Depending on how different the display should be from the defaults there may be few or many of these templates in the theme. The concept of overrides lets themers selectively change displays without having to create tempaltes for the entire site.'] = 'sont les modèles qui affichent le contenu des blocs et des modules. Ils remplacent les modèles par défaut déjà présents dans les blocs et modules respectifs. Dépendant de comment l\'affichage devrait être différent de celui par défaut il peut y avoir quelque ou plusieurs de ces modèles dans le thème. Le concept du remplacement laisse la sélection du thème changer l\'affichage sans avoir à créer des modèles pour le site entier.';
$xarML_PHPBackend_entries['The Admin interface'] = 'L\'interface de l\'Admin';
$xarML_PHPBackend_entries['As an administrator, you can change the module\'s configuration by pointing your browser to the configuration page'] = 'En tant qu\'administrateur, vous pouvez changer la configuration du module en pointant votre navigateur vers une page de configuration';
$xarML_PHPBackend_entries['Admin Menu → Themes → Modify Configuration'] = 'Menu Admin  → Thèmes  →  Modifier la Configuration';
$xarML_PHPBackend_entries['. The configuration page includes the standard display options common to all core modules (see the Base module overview for an explanation of these).'] = '. La page de configuration inclut les options d\'affichage standadrd commune à tous les modules du noyau (voir l\'aperçu du  module de base pour une explication de ceux-ci.';
$xarML_PHPBackend_entries['In addition, this module also supports the following configuration options:'] = 'En plus, ce module supporte aussi les options de configuration suivantes :';
$xarML_PHPBackend_entries['Enable user settings:'] = 'Activer les paramètres de l\'utilisateur';
$xarML_PHPBackend_entries[' If this option is active, then users can define the theme to view the site with from their account page'] = 'Si cette option est active, alors les utilisateurs peuvent définir le thème avec lequel voir le sire à partir de la page de compte';
$xarML_PHPBackend_entries['Admin Dashboard'] = 'Tableau be bord Admin';
$xarML_PHPBackend_entries['Enable the Admin Dashboard:'] = 'Activer le Tableau be bord Admin';
$xarML_PHPBackend_entries[' The Admin Dashboard is a special theme
that uses the dashboard.xt template (by default) if it exists in your themes/yourtheme/pages directory. If you check this option the Admin Dashboard provides admin options in a special Admin page view instead of through the Admin Menu.'] = 'Le Tableau de bord Admin est un thème spécial qui utilise le modèle dashboard.xt (par défaut) s\'il existe dans votre registre thèmes/vosthèmes/pages. Si vous cochez cette option dans le tableau de bord Admin fournit des option admin dans un aperçu de page spécial Admin au lieu utiliser le menu Admin.';
$xarML_PHPBackend_entries['Dashboard Template Name:'] = 'Nom du modèle du tableau de bord :';
$xarML_PHPBackend_entries[' This is the name of the Admin Dashboard
template located in your themes/yourtheme/pages directory. By default it is called
dashboard.xt, but you can change it with this option. Do not include the .xt extension in the name when using this option.'] = 'C\'est le nom du modèle du tableau de bord : localiser dans le registre thèmes/vosthèmes/pages. Par défaut il est appelé dashboard.xt, mais vous pouvez le changer avec cette option. Ne pas inclure l\'extension .xt  dans le nom quand vous utilisez cette option.';
$xarML_PHPBackend_entries[' These are variables that can be inserted into your templates for display on your site. They are all used in the Default theme at installation time. To display these variables on your site, insert them in your templates with the appropriate'] = 'C,est des variables qui peuvent être inséré dans vos modèles pour affichage sur votre site. Elles sont tous utilisés dans le thème par Défaut au moment de l\'installation. Pour afficher ces variables sur votre site, insérer-les dans vos modèles avec l\'approprié';
$xarML_PHPBackend_entries['<xar:var />'] = '<xar:var />';
$xarML_PHPBackend_entries['blocklayout tag.'] = 'étiquette de diaposition de bloc';
$xarML_PHPBackend_entries['<xar:var scope="module" module="themes" name="SiteName" />'] = '<xar:var scope="module" module="themes" name="SiteName" />';
$xarML_PHPBackend_entries['<xar:var scope="module" module="themes" name="SiteSlogan" />'] = '<xar:var scope="module" module="themes" name="SiteSlogan" />';
$xarML_PHPBackend_entries[': Defaults to "© Copyright 2009 <administrator name>".
Change the text as necessary and insert in your theme with'] = ': Défauts des "© Droits d\'auteurs 2009 <administrator name>". Changer le texte si c\'est nécessaire et insérer votre thème avec';
$xarML_PHPBackend_entries['<xar:var scope="module" module="themes" name="SiteCopyRight" />'] = '<xar:var scope="module" module="themes" name="SiteCopyRight" />';
$xarML_PHPBackend_entries['Footer note'] = 'note de Pied de page';
$xarML_PHPBackend_entries[': The \'footer\' is displayed at the bottom (the \'foot\') of every page on your site in the Default theme.'] = ': Le \'pied de page\' est affiché au bas (le \'pied\') de chaque page de votre site dans le thème par défaut.';
$xarML_PHPBackend_entries['<xar:var scope="module" module="themes" name="SiteFooter" />'] = '<xar:var scope="module" module="themes" name="SiteFooter" />';
$xarML_PHPBackend_entries['Page Title Options'] = 'Options de titre de page';
$xarML_PHPBackend_entries['Page Title Separator:'] = 'Séparateur de titre de page';
$xarML_PHPBackend_entries[' defines the separation character(s) in your
page titles. Example: "Themes :: Your Site Slogan :: Your Site Name"'] = 'définir la séparation de caractère (s) dans votre page de titres. Exemple: \'\'Thèmes :: Le Slogan de votre site :: Le nom de votre site\'\'';
$xarML_PHPBackend_entries['Page Title Order:'] = 'Ordre de titre de page';
$xarML_PHPBackend_entries[' defines how the page titles are displayed (e.g. site name - page name). You can choose from a dropdown of several options.'] = 'défini comment la page de titre est affichée ( ex nom du site- nom de la page). Vous pouvez choisir plusieures options de la liste déroulante.';
$xarML_PHPBackend_entries['Template Caching Options'] = 'Options de modèles de Cache';
$xarML_PHPBackend_entries['Cache compiled templates:'] = 'Modèles de cache compilé';
$xarML_PHPBackend_entries[' This option enables caching of templates. It
is important for performance that you have Cache Templates checked and active
on a site. Turn it off when developing your theme.'] = 'Cette option active la cache des modèles. Il est important que vous ayez des modèles de Cache vérifiées et actifs sur le site. Éteignez-le quand vous développez votre thème.';
$xarML_PHPBackend_entries['Enable memory caching for templates:'] = 'Activer la mémoire cache pour les modèles';
$xarML_PHPBackend_entries[' This option enables caching of
compiled templates in memory during a single page request, which might (or might not)
improve performance on your site. This option is'] = 'Cette option active la cache des modèles compilés dans la mémoire';
$xarML_PHPBackend_entries['experimental'] = 'expérimental';
$xarML_PHPBackend_entries['Template Debugging Options'] = 'Options de débogage de modèle';
$xarML_PHPBackend_entries['Show php comment block header in compiled templates:'] = 'Afficher l\'en-tête du bloc de commentaire php dans les modèles compilés:';
$xarML_PHPBackend_entries[' This
feature enables you to inspect a compiled template and know which template it
refers to.'] = 'Cette fonction vous permet d\'inspecter un modèle compilé et de savoir à quel modèle il réfère.';
$xarML_PHPBackend_entries['Show template filenames in HTML comments:'] = 'Afficher les modèles des noms des fichiers dans les commentaires HTML:';
$xarML_PHPBackend_entries[' When you view the
source of a page, checking this option will display the start and end point of
each template used in the page. This is useful for identifying which
template to override and edit when you need to customize your theme. This
option should be turned off on a live site.'] = 'Quand vous visionnez la source de la page, cocher cette option affichera le point de début et de fin de chaque modèle utilisé dans cette page. Cela est utile pour identifier chaque modèle pour remplacer et éditer quand vous avez besoin de personnalisé votre thème. Cette option devrait être fermé sur un site en direct.';
$xarML_PHPBackend_entries['Debug Templates by showing variables available:'] = 'Déboguer les modèles en affichant les variables disponible:';
$xarML_PHPBackend_entries[' Shows the variables
used in each template which is handy for debugging template errors.'] = 'Afficher les variables utilisés dans chaque modèle ce qui est utile pour déboguer les erreurs des modèls.';
$xarML_PHPBackend_entries['Clicking on the'] = 'Cliquer sur le';
$xarML_PHPBackend_entries['link in the Admin menu displays a list of all themes that are available but not necessarily active and installed in your Xaraya installation.'] = 'Un lien dans le menu Admin afficher une liste de tous les thèmes qui sont disponibles mais pas nécessairement actif et installé dans votre installation Xaraya.';
$xarML_PHPBackend_entries['You can add more themes to this list at any time by adding them to your Xaraya
themes directory and clicking the Refresh button'] = 'Vous pouvez ajouter plus de thèmes à cette liste à n\'importe quel moment en les ajoutant à votre registre de thèmes Xaraya et en cliquant sur le bouton actualiser.';
$xarML_PHPBackend_entries['Themes must be initialized and active to be available for use on your Xaraya
site.'] = 'Les thèmes doivent être initialisés et activé pour être disponible sur le site de Xaraya.';
$xarML_PHPBackend_entries['Within the list of themes you can view further information on each theme by clicking on its link in the Info column.
If more than one theme is active, the themes the site is'] = 'Dans la liste des thèmes vous pouvez visionner plus d,information sur chaque thème en cliquant sur son lien dans la colonne d\'info. Si plus d\'un thème est actif, les thèmes du site sont';
$xarML_PHPBackend_entries['not'] = 'pas (ne pas)';
$xarML_PHPBackend_entries['displayed in by default will have a Set as Default link in the Actions column. Clicking on the link will make that theme the default theme for displaying the site.'] = 'affiché par défaut sera paramètrer comme un lien par défaut dans la colonne Admin. Cliquer sur le lien qui feront de ce thème le thème par déafut pour affichage sur le site.';
$xarML_PHPBackend_entries['The controls at the top of the display offer a number of options for viewing themes:'] = 'Les contrôles en haut de l\'affichage offre un nombre d\'options pour visionner les thèmes';
$xarML_PHPBackend_entries['Style:'] = 'Style:';
$xarML_PHPBackend_entries[' show a simple listing or display each item with a thumbnail of the theme (if one exists).'] = 'afficher une liste simple ou afficher chaque objet avec une image miniature (s\'il en existe une)';
$xarML_PHPBackend_entries['View:'] = 'Aperçu:';
$xarML_PHPBackend_entries[' a dropdown with a number of filtering options for displaying only certain themes.'] = 'une liste déroulante avec un nombre d\'options de filtrage pour afficher certains thèmes seulement.';
$xarML_PHPBackend_entries[' a dropdown that filters and displays themes by their class (System, Utility, User).'] = 'une liste déroulante qui filtre et affiche les thèmes selon leur classe (Système,Utilité,Utilisateur)';
$xarML_PHPBackend_entries['Use Icons:'] = 'Icônes Utilisés:';
$xarML_PHPBackend_entries[' when checked substitutes the text links on the page with icon links.'] = 'quand il y a vérification substituer les liens de texte sur cette page avec des liens d\'icônes.';
$xarML_PHPBackend_entries['Available Blocks'] = 'Blocs disponibles:';
$xarML_PHPBackend_entries['Meta Block:'] = 'Bloc Meta:';
$xarML_PHPBackend_entries[' installed by default, this block lets you enter a meta description for your site, activate GEOUrl and set usability pages. You can also set keywords for the site manually or activate dynamic keywords supplied by the Articles, Keywords or other modules that support keywords.'] = 'installé par défaut, ce bloc vous laisse entrer une description meta sur votre site, activer GEOUrl et paramètrer les pages d\'utilisation. Vous pouvez aussi paramètrer les mots clés pour le site manuellement ou activer les mots clés dynamique fournient par les articles, les mots clés et autres modules qui supporte des mots clés.';
$xarML_PHPBackend_entries['Available Dataproperties'] = 'propriétés de données  disponible';
$xarML_PHPBackend_entries['The Themes module has no dataproperties'] = 'Les thèmes du module n\'a pas de propriétés de données';
$xarML_PHPBackend_entries['Available Hooks'] = 'Crochets disponibles';
$xarML_PHPBackend_entries['The Themes module has no hooks'] = 'Les thèmes du module n\'a pas de crochets';
?>