<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Flat Cables'] = 'Systèmes de câblage';
$xarML_PHPBackend_entries['Building Automation'] = 'Gestion technique du bâtiment';
$xarML_PHPBackend_entries['Safety Systems'] = 'Systèmes de protection au feu';
$xarML_PHPBackend_entries['Routing Systems'] = 'Systèmes de guidage de câbles';
$xarML_PHPBackend_entries['Connection Systems'] = 'Solutions de raccordement';
$xarML_PHPBackend_entries['Choose Country'] = 'Choisir Pays';
$xarML_PHPBackend_entries['Flat Cable Systems'] = 'Systèmes de câblage';
$xarML_PHPBackend_entries['Building Automation Systems'] = 'Gestion technique du bâtiment';
$xarML_PHPBackend_entries['Products for Third Parties'] = 'Production pour tiers';
$xarML_PHPBackend_entries['Downloads'] = 'Téléchargement';
$xarML_PHPBackend_entries['Products'] = 'Produits';
$xarML_PHPBackend_entries['Company'] = 'Entreprise';
$xarML_PHPBackend_entries['References'] = 'Références';
$xarML_PHPBackend_entries['Contact'] = 'Contact';
$xarML_PHPBackend_entries['Philosophy'] = 'Philosophie';
$xarML_PHPBackend_entries['History'] = 'Historique';
$xarML_PHPBackend_entries['Innovation'] = 'Nouveautés';
$xarML_PHPBackend_entries['Current Vacancies'] = 'Offres d\'emploi';
$xarML_PHPBackend_entries['Terms and Conditions'] = 'Conditions générales de vente';
$xarML_PHPBackend_entries['Headquarters'] = 'Siège';
$xarML_PHPBackend_entries['Switzerland'] = 'Suisse';
$xarML_PHPBackend_entries['Export-Team'] = 'Service export';
$xarML_PHPBackend_entries['Subsidiaries'] = 'Filiales';
$xarML_PHPBackend_entries['Contact Form'] = 'Formulaire prise de contact';
$xarML_PHPBackend_entries['Requirements'] = 'Exigences';
$xarML_PHPBackend_entries['Concept'] = 'Concept';
$xarML_PHPBackend_entries['Functional Principle'] = 'Principe de fonctionnement';
$xarML_PHPBackend_entries['Contact Technology'] = 'Techniques de contact';
$xarML_PHPBackend_entries['New Generation'] = 'Nouvelle génération';
$xarML_PHPBackend_entries['Range'] = 'Gamme';
$xarML_PHPBackend_entries['Sender Name'] = 'Nom';
$xarML_PHPBackend_entries['Subject'] = 'Sujet';
$xarML_PHPBackend_entries['Message'] = 'Message';
$xarML_PHPBackend_entries['Sender Email'] = 'Email';
$xarML_PHPBackend_entries['Choose a download'] = 'Choisir un téléchargement';
?>