<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Flat Cables'] = 'Flachkabel';
$xarML_PHPBackend_entries['Safety Systems'] = 'Brandsicherheitssysteme';
$xarML_PHPBackend_entries['Routing Systems'] = 'Kabelführungssysteme';
$xarML_PHPBackend_entries['Connection Systems'] = 'Komponenten Installationstechnik';
$xarML_PHPBackend_entries['Choose Country'] = 'Land wählen';
$xarML_PHPBackend_entries['Flat Cable Systems'] = 'Flachkabelsysteme';
$xarML_PHPBackend_entries['Building Automation Systems'] = 'Gebäudeautomation';
$xarML_PHPBackend_entries['Products for Third Parties'] = 'Produkte für Dritte';
$xarML_PHPBackend_entries['Downloads'] = 'Downloads';
$xarML_PHPBackend_entries['Products'] = 'Produkte';
$xarML_PHPBackend_entries['Company'] = 'Unternehmen';
$xarML_PHPBackend_entries['References'] = 'Referenzen';
$xarML_PHPBackend_entries['Contact'] = 'Kontakt';
$xarML_PHPBackend_entries['Home'] = 'Home';
$xarML_PHPBackend_entries['News'] = 'News';
$xarML_PHPBackend_entries['Shop'] = 'Shop';
$xarML_PHPBackend_entries['Philosophy'] = 'Grundidee';
$xarML_PHPBackend_entries['History'] = 'Geschichte';
$xarML_PHPBackend_entries['Innovation'] = 'Innovation';
$xarML_PHPBackend_entries['Current Vacancies'] = 'Karriere';
$xarML_PHPBackend_entries['Terms and Conditions'] = 'AGB';
$xarML_PHPBackend_entries['ISO Certification'] = 'ISO Zertifizierung';
$xarML_PHPBackend_entries['Headquarters'] = 'Hauptsitz';
$xarML_PHPBackend_entries['Switzerland'] = 'Schweiz';
$xarML_PHPBackend_entries['Subsidiaries'] = 'Niederlassungen';
$xarML_PHPBackend_entries['Contact Form'] = 'Kontaktformular';
$xarML_PHPBackend_entries['Services'] = 'Dienstleistungen';
$xarML_PHPBackend_entries['Requirements'] = 'Anforderungen';
$xarML_PHPBackend_entries['Concept'] = 'Grundidee';
$xarML_PHPBackend_entries['Functional Principle'] = 'Funktionsprinzip';
$xarML_PHPBackend_entries['Contact Technology'] = 'Kontaktierung';
$xarML_PHPBackend_entries['New Generation'] = 'Neue Generation';
$xarML_PHPBackend_entries['System Guarantee'] = 'Systemgarantie';
$xarML_PHPBackend_entries['Range'] = 'Sortiment';
$xarML_PHPBackend_entries['Sender Name'] = 'Absender Name';
$xarML_PHPBackend_entries['Subject'] = 'Betreff';
$xarML_PHPBackend_entries['Message'] = 'Nachricht';
$xarML_PHPBackend_entries['Sender Email'] = 'Absender Email';
$xarML_PHPBackend_entries['This item cannot be viewed'] = 'Diese Seite kann nicht eingesehen werden';
$xarML_PHPBackend_entries['Back'] = 'Zurück';
$xarML_PHPBackend_entries['Description'] = 'Beschreibung';
$xarML_PHPBackend_entries['Choose a download'] = 'Datei wählen';
?>