<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Empty regid (#(1)).'] = 'Regid (#(&)) vide';
$xarML_PHPBackend_entries['Unable to execute "activate" function in the xarinit.php file of module (#(1))'] = 'Impossible d\'executer la fonction "Activer" dans le fichier xarinit.php du module (#(1))';
$xarML_PHPBackend_entries['Module name #(1) is already in use'] = 'Nom de module #(1) déjà utilisé';
$xarML_PHPBackend_entries['Missing module regid (#(1)).'] = 'Regid (#(1)) du module manquant.';
$xarML_PHPBackend_entries['Module to be deactivated (#(1)) is not active nor upgraded'] = 'Le module à désactiver (#(1)) n\'est ni actif ni à jour';
$xarML_PHPBackend_entries['Unable to deactivate module "#(1)".'] = 'Impossible de désactiver le module "#(1)".';
$xarML_PHPBackend_entries['callerModName or hookModName'] = 'appelModName ou crochetModName';
$xarML_PHPBackend_entries['Unable to get dependencies for module with ID (#(1)).'] = 'Impossible de récupérer les dépendances pour le module avec l\'ID (#(1)).';
$xarML_PHPBackend_entries['View list of all installed modules on the system'] = 'Voir la liste de tous les modules installés sur le système';
$xarML_PHPBackend_entries['View All'] = 'Voir tout';
$xarML_PHPBackend_entries['Set various options'] = 'Configurer les options';
$xarML_PHPBackend_entries['Extend the functionality of your modules via hooks'] = 'Etendre les fonctionnalités de vos modules grâce aux crochets';
$xarML_PHPBackend_entries['Configure Hooks'] = 'Configurer les crochets';
$xarML_PHPBackend_entries['Use these tools to build and verify elements of modules.'] = 'Utilisez ces outils pour construire et vérifier les éléments des modules.';
$xarML_PHPBackend_entries['View recent release information for certified modules within the last week.'] = 'Voir les informations sur les modules certifiés sorties durant la dernière semaine.';
$xarML_PHPBackend_entries['Certified Releases'] = 'Sorties certifiées';
$xarML_PHPBackend_entries['The dependencies to initialize the module "#(1)" were not met.'] = 'Les dépendances pour initialiser le moduyle "(#1)" n\'ont pas été atteintes.';
$xarML_PHPBackend_entries['Module initialisation failed because the function (#(1)) returned false'] = 'L\'initialisation du module a échoué car la fonction (#(1)) à renvoyé False';
$xarML_PHPBackend_entries['Module initialisation failed because your module did not include an init function'] = 'L\'initialisation du module a échoué car votre module ne contient pas de fonction d\'initialisation';
$xarML_PHPBackend_entries['Module state change failed'] = 'Le changement d\'état du module a échoué';
$xarML_PHPBackend_entries['Unable to initialize dependecy module with ID (#(1)).'] = 'Impossible d\'initialiser les dépendances du module avec l\'ID (#(1)).';
$xarML_PHPBackend_entries['Unable to initialize module "#(1)".'] = 'Impossible d\'initialiser le module "#(1)".';
$xarML_PHPBackend_entries['Unable to activate module "#(1)".'] = 'Impossible d\'activer le module "#(1)".';
$xarML_PHPBackend_entries['Empty regid (#(1)) or state (#(2)).'] = 'Regid (#(1)) ou état (#(2)) vide.';
$xarML_PHPBackend_entries['Invalid module state transition'] = 'Etat de transition de module invalide';
$xarML_PHPBackend_entries['Invalid module name'] = 'Nom de module invalide';
$xarML_PHPBackend_entries['No such module'] = 'Pas de tel module';
$xarML_PHPBackend_entries['Module has been upgraded, now inactive'] = 'Le module a été mis à jour, il est maintenant inactif';
?>