<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Modules'] = 'Modules';
$xarML_PHPBackend_entries['None'] = 'Aucun';
$xarML_PHPBackend_entries['Save Changes'] = 'Enregistrer les changements';
$xarML_PHPBackend_entries['as provided by the author'] = 'comme fourni par l\'auteur';
$xarML_PHPBackend_entries['Only generic icon has been provided'] = 'Seul l\'icône par défaut à été fourni';
$xarML_PHPBackend_entries['Working on it...'] = 'En cours...';
$xarML_PHPBackend_entries['Module'] = 'Module';
$xarML_PHPBackend_entries['Preferences'] = 'Préférences';
$xarML_PHPBackend_entries['Modules List'] = 'Liste des modules';
$xarML_PHPBackend_entries['Style:'] = 'Style :';
$xarML_PHPBackend_entries['View number of modules per page:'] = 'Voir le nombre de modules par page :';
$xarML_PHPBackend_entries['Restore'] = 'Restaurer';
$xarML_PHPBackend_entries['Status: your current preferences are the same as defaults'] = 'Statut : vos préférences actuelles sont les mêmes que celles par défaut.';
$xarML_PHPBackend_entries['View Modules'] = 'Voir les Modules';
$xarML_PHPBackend_entries['Hooks'] = 'Crochets';
$xarML_PHPBackend_entries['Name'] = 'Nom';
$xarML_PHPBackend_entries['Display Name'] = 'Nom Affiché';
$xarML_PHPBackend_entries['Version'] = 'Version';
$xarML_PHPBackend_entries[' '] = '.';
$xarML_PHPBackend_entries['Dependents still Active'] = 'Dépendances encore actives';
$xarML_PHPBackend_entries['Go back to the modules list'] = 'Retour à la liste des modules';
$xarML_PHPBackend_entries['['] = '[';
$xarML_PHPBackend_entries[']'] = ']';
$xarML_PHPBackend_entries['Configure Hooks'] = 'Configurer les Crochets';
$xarML_PHPBackend_entries['By checking this box a logout link will be shown in the panel instance.'] = 'En cochant cette case un lien de déconnexion sera affiché dans le panneau d\'aide .';
$xarML_PHPBackend_entries['Show a logout link in this menu'] = 'Afficher le  lien de déconnexion dans ce menu';
$xarML_PHPBackend_entries['By checking this box the menu will NOT show the overview page of the module by default.'] = 'En cochant cette case  le menu ne sera pas afficher dans la page d\'apperçu dans le module par défaut.';
$xarML_PHPBackend_entries['Disable the module overview by default'] = 'Désactiver l\'apperçu de menu par défaut';
$xarML_PHPBackend_entries['How should the menu items be ordered?'] = 'Comment les items de menu devraient-ils être trié?';
$xarML_PHPBackend_entries['Sort menuitems:'] = 'Trier les menuitems:';
$xarML_PHPBackend_entries['Click to toggle display of available hooks for this module.'] = 'Cliquer pour l\'affichage plein écran des crochets disponibles pour ce module.';
$xarML_PHPBackend_entries['Details'] = 'Détails';
$xarML_PHPBackend_entries['The #$modinfo[\'displayname\']# module supplies the following hooks...'] = 'Le module #$modinfo[\'displayname\']#  fournit les crochets suivants...';
$xarML_PHPBackend_entries['Itemtype #$itemtype#: #$typeinfo[\'label\']#'] = 'Itemtype #$itemtype#: #$typeinfo[\'label\']#';
$xarML_PHPBackend_entries['Logout as administrator'] = 'Se déconnecter comme administrateur';
$xarML_PHPBackend_entries['Admin logout'] = 'Déconnexion Admin';
?>