<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Official Icon'] = 'Icône officiel';
$xarML_PHPBackend_entries['Overview'] = 'Aperçu';
$xarML_PHPBackend_entries['Overview:'] = 'Aperçu';
$xarML_PHPBackend_entries['About'] = 'À propos';
$xarML_PHPBackend_entries['Admin'] = 'Admin';
$xarML_PHPBackend_entries['How To'] = 'Comment';
$xarML_PHPBackend_entries['What is it?'] = 'Quest-ce que c\'est?';
$xarML_PHPBackend_entries['The Blocks module lets site administrator(s) create and manage the configuration, display position and grouping of \'blocks\' of content or functionality on a Xaraya site. The Blocks module is a core module within
Xaraya and cannot be removed.'] = 'Le module des blocs laisse le(s) adminitrateur(s) du site créer et gérer la configuration, la position d\'affichage et le regroupement des blocs du contenu ou la fonctionnalité sur un site Xaraya. Le module des blocs est un module du noyau avec Xaraya et ne peut être supprimer.';
$xarML_PHPBackend_entries['Detail information on this module can be found'] = 'De l\'information détaillée sur ce module peut être trouvé';
$xarML_PHPBackend_entries['Concepts'] = 'Concepts';
$xarML_PHPBackend_entries['A block type defines a specific display of content or functionality that you can place on your site. Xaraya modules can provide their own block types. For example the Blocks module provides a \'blockgroup\' block type to create blocks that are used to display and manage blockgroups. The Base module provides a \'menu\' block type for displaying menus, and so on.'] = 'Un type de bloc défini un affichage spécifique du contenu ou de la fonctionnalité que vous pouvez placer sur votre site. Les modules Xaraya peuvent fournir leurs propres types de bloc. Par exemple le module des blocs fournit un type de bloc de \'groupe de bloc\' pour créer des blocs qui sont utilisés pour afficher et gérer les groupes de bloc. Le module de base fournit un \'menu. de  type de bloc pour l\'affichage des menus, et ainsi de suite.';
$xarML_PHPBackend_entries['A module\'s block types are available when the module is installed, and removed when it is uninstalled. Block types are managed through the'] = 'Des types de blocs de module sont dispnibles quand le module est installé, et supprimé quand il est désinstallé. Les types de blocs sont gérés à travers la';
$xarML_PHPBackend_entries['page, which lists all the block types available in your Xaraya installation and the modules they belong to.'] = 'page, qui liste tous les types de bloc disponibles dans votre installation Xaraya et les modules auxquels ils appartiennent.';
$xarML_PHPBackend_entries['A block is an instance of a block type. You can create as many blocks from a given block type as required, each with its own behavior and content (several menu block on the same page, for instance). In general blocks are displayed on a site\'s pages by assigning them to one or more block group, but a block can also be displayed anywhere on a page by using a block tag (see'] = 'Un bloc est une instance d\'un type de bloc. Vous pouvez créer autant de blocs d\'un type de bloc donné comme requis, chacun avec son propre comportement et conteny (plusieurs menu de bloc sur la même page, pour instance). En général les blocs sont affichés sur les pages de site en les assignant à un ou plusieurs groupe de bloc, mais un bloc peut aussi être affiché n\'importe où sur la pahe en utilisant une étiquette de bloc (voir';
$xarML_PHPBackend_entries['RFC0010'] = 'RFC0010';
$xarML_PHPBackend_entries['for details about using block and block group tags).'] = 'pour des détails sur comment utiliser les étiquettes de bloc et  groupes de bloc';
$xarML_PHPBackend_entries['Available Blocks'] = 'Blocs disponibles';
$xarML_PHPBackend_entries['The Blocks Module has the following blocks'] = 'Le module des blocs a les blocs suivants';
$xarML_PHPBackend_entries['Blockgroup Block'] = 'Bloc de groupe de bloc';
$xarML_PHPBackend_entries['- Responsible for displaying and managing blockgroups'] = '-  Responsable de l\'affichage et de la gestion des groupes de bloc';
$xarML_PHPBackend_entries['Block groups are clusters of blocks on your site\'s pages. The blocks assigned to a given group are all displayed in the area of a page that group occupies. Xaraya comes pre-configured with block groups created at installation time that include'] = 'Les groupes de bloc sont des blocs de stockage de données sur un disque  pour les pages de votre site. Les blocs assignés à un bloc donnée sont tous affichés dans une zone de la page qu\'un groupe occupe. Xaraya vient pré-configuré avec les groupes de bloc créés au moment de l\'installation qui inclut';
$xarML_PHPBackend_entries['right'] = 'droit';
$xarML_PHPBackend_entries[','] = ',';
$xarML_PHPBackend_entries['left'] = 'gauche';
$xarML_PHPBackend_entries['center'] = 'centre';
$xarML_PHPBackend_entries['topnav'] = 'visibilité';
$xarML_PHPBackend_entries['and'] = 'et';
$xarML_PHPBackend_entries['header'] = 'en-tête';
$xarML_PHPBackend_entries['block groups. Block group tags are used in theme pages to postion and display each group and its blocks (the name of a group can be changed but must be unique). A block can be assigned to more than one group and is displayed in each group it is assigned to.'] = 'groupes de bloc. Les étiquettes de groupe de bloc sont utilisées dans les thèmes des pages pour positionner et afficher les chacun des groupes et ses blocs (le nom d\'un groupe peut être changé mais il doit être unique). Un bloc peut être assigné à plus d\'un grroupe et est affiché dans chaque groupe auquel il a été assigné.';
$xarML_PHPBackend_entries['Available Dataproperties'] = 'Propriétés de données disponibles';
$xarML_PHPBackend_entries['The Blocks module has no dataproperties'] = 'Le module des blocs n\'a pas de propriétés de données';
$xarML_PHPBackend_entries['Available Hooks'] = 'Crochets Disponibles';
$xarML_PHPBackend_entries['The Blocks module has no hooks'] = 'Le modules des blocs n\'a pas de crochets';
$xarML_PHPBackend_entries['The Admin interface'] = 'L\'interface de l\'Admin';
$xarML_PHPBackend_entries['View Blocks'] = 'Voir les blocs';
$xarML_PHPBackend_entries['Clicking on the'] = 'Cliquer sur le';
$xarML_PHPBackend_entries['link in the Admin menu displays all the current blocks that are available for use in your Xaraya site and lets you modify or delete them. The page also has a link to the'] = 'lien dans le menu Admin affiche tous les blocs actuels qui sont disponibles pour utilisation dans votre site Xaraya et vous laisse les modifier ou les supprimer. La pages a aussi un lien à la';
$xarML_PHPBackend_entries['New Block'] = 'Nouveau Bloc';
$xarML_PHPBackend_entries[' page. You can go to a block\'s configuration page by clicking on its Edit link in the list of blocks displayed. See'] = 'page. Vous pouvez aller à la page de configuration du bloc en cliquant sur son lien Éditer dans la liste des blocs affichés. Voir';
$xarML_PHPBackend_entries['Block Configuration'] = 'Configuration du bloc';
$xarML_PHPBackend_entries['for details.'] = 'pour les détails.';
$xarML_PHPBackend_entries['link in the Admin menu lets you create and make available a new block of a given block type, and optionally assign it to a block group. See'] = 'Un lien dans le menu Admin vous laisse créer et rendre disponible un nouveau bloc d\'un type de bloc donné, et vous pouvez optionnellement l\'assigner à un groupe de bloc. Voir';
$xarML_PHPBackend_entries['link in the Admin menu displays all the defined Block Types on your site with a link to a detail display of each Block Type\'s configuration. The page also contains a link to the'] = 'le lien dans le menu Admin affiche tous les types de bloc défini sur votre site avec un lien ver l\'affichage détaillé de chaque configuration du type de bloc. Cette page contient aussi un lien à la';
$xarML_PHPBackend_entries['page, which can scan a module for its block types and lets you add any that are not yet available. Xaraya does not actually allow you to create new block types. Rather, this option is used in the (exceptional) case when a block type was not properly installed in the course of a normal module release or upgrade.'] = 'page, qui peut scanner un module pour ces types de bloc, et vous laisse ajouter n\'importe quel qui ne sont pas encore disponibles. Xaraya ne vous permet pas vraiment de créer de nouveaux types de bloc. À la place, cette option est utilisée dans le case (exceptionnel) quand un type de bloc n\'est pas installé correctement dans le cour normale d\'une sortie de module ou d\'une mise à jour.';
$xarML_PHPBackend_entries['Modify Configuration'] = 'Modifier la configuration';
$xarML_PHPBackend_entries['As an administrator, you can change the module\'s configuration by pointing your browser to the configuration page'] = 'En tant qu\'administrateur, vous pouvez changer la configuration du module en pointant votre navigateur dans la page de configuration.';
$xarML_PHPBackend_entries['Admin Menu → Blocks → Modify Configuration'] = 'Menu Admin→ Blocs → Modifer la  Configuration';
$xarML_PHPBackend_entries['. The configuration page includes the standard display options common to all core modules (see the Base module overview for an explanation of these).'] = '.La page de configuration inclut les options d\'affichage commun à tous les modules de noyau (voir l\'aperçu du module de base pour une explication de ceux-ci)';
$xarML_PHPBackend_entries['Creating a Block'] = 'Créer un Bloc';
$xarML_PHPBackend_entries['There are a number of steps required to create a new block of content or functionality
for your site, and display it:'] = 'Il y a un nombre d\'étapes requises pour créer un nouveau bloc de contenu ou de fonctionnalité pour votre site, et l\'afficher';
$xarML_PHPBackend_entries['Go to'] = 'Aller à';
$xarML_PHPBackend_entries['Admin Menu → Blocks → New Block'] = 'Menu Admin→ Blocs → Nouveau Bloc';
$xarML_PHPBackend_entries['and create a new block instance based on one of your installed block types.'] = 'et créer une nouvelle instance de bloc basé sur un des tupes de bloc installés.';
$xarML_PHPBackend_entries['Assign the block instance to an existing block group,either when you create it or at any later time. Make sure its state is "Maximize" so that it is displayed.'] = 'Assigner les instances de bloc à un groupe de bloc existant, quand vous le créez ou à n\'importe quel moment par après. Soyez sûr que son état est \'\'maximiser\'\' pour qu\'il soit affiché';
$xarML_PHPBackend_entries['If you need a new block group for displaying the block, create one and then assign the block to it'] = 'Si vous avez de besoin d\'un nouveau groupe de bloc pour afficher le bloc, créer s\'en un, et ensuite assigner y le bloc';
$xarML_PHPBackend_entries['Add a'] = 'Ajouter un';
$xarML_PHPBackend_entries['blockgroup tag'] = 'étiquette de groupe de bloc';
$xarML_PHPBackend_entries['in your theme template so Xaraya knows where to display
your blocks. e.g.'] = 'dans votre modèle de thème pour que Xaraya sache où afficher vos blocs. e.x.';
$xarML_PHPBackend_entries['<xar:blockgroup name="right" id="right" />'] = '<xar:blockgroup name="right" id="right" />';
$xarML_PHPBackend_entries['Note: you do not have to allocated a block instance to a block group. You can place the block directly into your theme templates by using a'] = 'Note: Vous n\'avez pas à allouer une instance de bloc à un groupe de bloc. Vous pouvez placer le bloc directement dans vos modèles de thème en utilisant un';
$xarML_PHPBackend_entries['block'] = 'bloc';
$xarML_PHPBackend_entries['tag (see'] = 'étiquette (voir';
$xarML_PHPBackend_entries['for details).'] = 'pour les détails).';
$xarML_PHPBackend_entries['Templating Blocks and Block Groups'] = 'Blocs des modèles et les groupes de bloc';
$xarML_PHPBackend_entries['As with other Xaraya content, you can provide your own override templates for blocks and the block groups they are assigned to.'] = 'Comme avec d\'autre contenu de Xaraya, vous pouvez fournir vos propres modèles pouvant être remplacées pour les blocs et les groupes de bloc auxquels ils sont assignés.';
$xarML_PHPBackend_entries['Inner template'] = 'modèle Interne';
$xarML_PHPBackend_entries[' is used for display of the content in a block, and is supplied by the module that provides the block type. It can be overridden like any other Xaraya template. Overrides for block inner templates should be be placed in'] = 'est utilisé pour afficher le contenu dans un bloc, et est fournit par le module qui fournit le type de bloc. Il peut être remplacé comme n\'importe quel autre modèle. Remplacer les modèles internes de bloc devrait être palcé dans';
$xarML_PHPBackend_entries['themes/[yourtheme]/modules/[themodule]/blocks'] = 'thèmes/[votre thème]/modules/[le module]/blocs';
$xarML_PHPBackend_entries['where [themodule] is the module providing the block type. The general name for the template is'] = 'où [lemodule] est le module fournissant le type de bloc. Le nom général pour le modèle est';
$xarML_PHPBackend_entries['blocktype-innertemplatename.xt'] = 'blocktype-innertemplatename.xt';
$xarML_PHPBackend_entries['Outer template'] = 'modèle externe';
$xarML_PHPBackend_entries[' is the name given to the template used for the block\'s block group. Some \'outer\' templates are installed by default with Xaraya, but you can also create your own \'outer\' templates. The outer templates are stored in your'] = 'Est le nom donné au modèle utilisé pour le bloc du groupe de bloc. Quelques modèles \'externes. sont installés par défaut avec Xaraya, mais vous pouvez aussi créer votre propre modèle \'externe.. Les modèles externes sont stockés dans votre';
$xarML_PHPBackend_entries['theme/[yourtheme]/blocks'] = 'thème/[votrethème]blocs';
$xarML_PHPBackend_entries['directory. If there is no specific block group template the block group will use the preinstalled \'default\' block group template.'] = 'registre. S\'il n\'y a pas de modèle de groupe de bloc spécifique l egroupe de bloc utilisera le modèle de groupe de bloc par défaut pré installé';
$xarML_PHPBackend_entries['How to tell Xaraya which inner and outer templates to use'] = 'Comment dire à Xaraya queles modèles interne ou externe utilisés';
$xarML_PHPBackend_entries['You can tell Xaraya which inner and outer templates to use when you create a new block instance or modify an existing one. Using the Blocks module, there are two places you can set either the inner template, the outer template or both.'] = 'Vous pouvez dire à Xaraya quels modèles entrants et sortans utiliés quand vous créez une nouvelles instance de bloc ou en modifiez un déjà existnt. En utilisant le module des blocs. il y a deux endroirs où vous pouvez configurer soit le modèle entrant soit le modèle sortant ou les deux.';
$xarML_PHPBackend_entries['The field labelled'] = 'Le champ étiquetté';
$xarML_PHPBackend_entries['Instance Template (optional):'] = 'Modèle d\'instance (optionnel)';
$xarML_PHPBackend_entries['sets the default inner and outer template
used for the block instance and any block group. You can specify inner, outer, both
inner and outer or none (leave empty) in the Inner and Outer fields respectively. Both are specified without the file extension.'] = 'paramétrer les modèles entrants et sortants utilisé par l\'instance de bloc ou n\'importe quel groupe de bloc. Vous pouvez spécifier l\'entrant, le sortant, les deux entrants et sirtants ou rien (laisser vide) dans les champs entrants et sortants respectifs. Les deux sont spécifiés dans le champ d\'extension.';
$xarML_PHPBackend_entries['If you add a block instance to a block group, another field will appear,
labelled with the name of the block group. You can add a specific inner, outer or
both inner and outer template in the Inner and Outer fields provided. Specifying an inner
or outer template in the block group template fields will override any other
templates.'] = 'Si vous ajoutez une instance de bloc à un groupe de blox, un autre champ apparaîtra, étiquetté avec le nom du groupe de bloc. Vous pouvez ajouter un modèle entrant, sortant ou entrant et sortant dans les champs entrants et sortants fournis. Spécifier le modèle entrant et sortant dans les champs de modèle du groupe de bloc seront remplacés par n\'importe quel autres modèlesé';
$xarML_PHPBackend_entries['An example:'] = 'Un exemple:';
$xarML_PHPBackend_entries['if you create a roles user block (which displays the current user\'s profile information) and you are using the default theme:'] = 'Si vous créez un bloc d\'utilisateur de rôles (qui affiche l\'information du profile de l\'utilisateur actuel) et vous utilisez le thème par défaut:';
$xarML_PHPBackend_entries['By default, this block will use the roles module\'s inner template called'] = 'par défaut, ce bloc utilisera le modèle  du module des rôles internes appelés';
$xarML_PHPBackend_entries['.xt'] = '.xt';
$xarML_PHPBackend_entries['located in'] = 'localisé dans';
$xarML_PHPBackend_entries['modules/roles/xartemplates/blocks'] = 'modules/rôles/modèlesxar/blocs';
$xarML_PHPBackend_entries['If you have allocated the user block to a block group called \'right\' it will use, by default,
the outer template located at'] = 'Si vous avez alloué le bloc d\'utilisateur ;a un groupe de bloc nommé \'droit\' il utilisera , par défaut le modèle externe localisé à';
$xarML_PHPBackend_entries['themes/default/blocks/'] = 'thèmes/défaut/blocs';
$xarML_PHPBackend_entries['If the \'right\' outer template does not exist it will use one called \'default.xt\' in that same directory.'] = 'Si le mod`le externe \'droit\' n\'existe pas le modèle appelé  \'default.xt\' sera utilisé dans le même registre';
$xarML_PHPBackend_entries['If you wish to override both outer and inner templates for the user block then you would specify,
for example, left in the Outer field and userprofile in the Inner field.
This would mean the outer template is one created and called'] = 'Si vous sohiatez remplacer les modèles externes et internes pour l\'utilisateur du bloc vous devriez spécifier, par exemple, gauche dans le profil externe et le profil de l\'utilisateur dans le champ interne. Cela signifiera que le modèle externe a été crée et est appelé';
$xarML_PHPBackend_entries['located in the directory'] = 'localisé dans le registre';
$xarML_PHPBackend_entries['themes/default/blocks'] = 'thèmes/défaut/blocs';
$xarML_PHPBackend_entries['The roles module\'s user block will be displayed using the template'] = 'L\'utilisateur du bloc du module des rôles sera affiché en utilisant le modèle';
$xarML_PHPBackend_entries['themes/default/modules/roles/blocks/user-'] = 'themes/default/modules/roles/blocks/user-';
$xarML_PHPBackend_entries['userprofile'] = 'profile d\'utilisateur';
$xarML_PHPBackend_entries['You could just specify outer or inner template if required by adding'] = 'Vous pouvez juste spécifier le modèle externe ou interne si requis an ajoutant';
$xarML_PHPBackend_entries['to the Outer field or'] = 'au champ externe pour';
$xarML_PHPBackend_entries['to the Inner field.'] = 'au champ interne.';
$xarML_PHPBackend_entries['Administrators can configure the following options per block instance from the Config tab available when editing a block.'] = 'Les administrateurs peuvent configurer les options suivantes pour chaque instance de bloc à partir de l\'onglet de Config disponible en éditant un bloc.';
$xarML_PHPBackend_entries['Block Properties'] = 'Propriétés du bloc';
$xarML_PHPBackend_entries['- String, name of the block (required), must be unique, lowercased and cannot contain spaces, maximum length 100 characters'] = '-Chaîne, nom du bloc (requis), doit être unique, en miniscules, et ne contenir aucun espace, longueur maximum 100 caractères';
$xarML_PHPBackend_entries['Title'] = 'Titre';
$xarML_PHPBackend_entries['- String, title of the block (optional), maximum length 255 characters'] = '-Chaîne, titre du bloc (optionnel) longueur maximum 255 caractères';
$xarML_PHPBackend_entries['Default State'] = 'État par défaut';
$xarML_PHPBackend_entries['- Int, state of module (required), options are'] = '-int, état du module (requis), options sont';
$xarML_PHPBackend_entries['Block Expiration'] = 'Expiration du bloc';
$xarML_PHPBackend_entries['string, set a time when block should stop being displayed (optional). Expects a string indicating the length of time to display the block for (from now) in the format'] = 'chaîne, paramétrer le temps où le bloc devrait arrêter d\'être affiché )optionnel). Prévoir une chaîne indiquant la longueur de temps pour afficher le bloc pour (à partir de maintenant) dans le format';
$xarML_PHPBackend_entries['ddd:hh:mm:ss'] = 'ddd:hh:mm:ss';
$xarML_PHPBackend_entries['. Once set the display shows the length of time left before the block expires, or a message that the block has expired. Setting to 0 means the block never expires (default).'] = '-Une fois que l\'affichage montre la la longueur du temps restant avant que le bloc expire, ou un message que le bloc ou un message que le bloc a expiré. Paramétrer à o signifie que le bloc n\'expire jamais(défaut)';
$xarML_PHPBackend_entries['Block type properties are supplied by the block being modified.'] = 'Les propriétés du type de bloc sont fournies par le bloc étant modifié.';
$xarML_PHPBackend_entries['Block Groups and Group Templates'] = 'Groupes de bloc et modèles de groupe';
$xarML_PHPBackend_entries['Add to Group'] = 'Ajouter au groupe';
$xarML_PHPBackend_entries['- Add this block to a blockgroup block.'] = '-Ajouter ce bloc à ce bloc de groupe de bloc';
$xarML_PHPBackend_entries['groupName Group Template'] = 'Modèle de Groupe de nom de groupe';
$xarML_PHPBackend_entries['- group specific outer and inner templates for this block when displayed in this blockgroup.'] = '- groupe de modèles externe et interne spécifique pour ce bloc quand vous affichés dans ce groupe de bloc.';
$xarML_PHPBackend_entries['Instance Template'] = 'Modèle d\'Instance';
$xarML_PHPBackend_entries['- Specify default outer and inner templates to use. Will be used when not over-ridden by a group template, falling back to default.xt.'] = '-Spécifier les modèles externes et internes par défaut à utiliser. Seront utilisés qaund ils ne sont pas remplacés par un modèle de groupe, retombant ainsi par défaut à xt.';
$xarML_PHPBackend_entries['See also...'] = 'Voir aussi...';
$xarML_PHPBackend_entries['Block Caching Configuration'] = 'Configuration de la cache du bloc';
$xarML_PHPBackend_entries['Block Access Configuration'] = 'Configuration de l\'accès au bloc';
$xarML_PHPBackend_entries['Administrators can configure caching per block instance from the Caching tab available when editing a block.'] = 'Les administrateurs peuvent configurer les instances de bloc de cache pour l\'onglet de cache disponible quand vous éditez un bloc.';
$xarML_PHPBackend_entries['The following caching options are available'] = 'Les options de cache suivantes sont disponibles';
$xarML_PHPBackend_entries['Disable Caching'] = 'Désactiver la cache';
$xarML_PHPBackend_entries['- When checked the block will not be cached.'] = '-Quand il est coché le bloc ne sera pas en cache.';
$xarML_PHPBackend_entries['- Optionally share the block across pages. If unchecked cache will take the request uri and request vars into account when caching blocks.'] = '_Paratager optionnellement le bloc à travers les pages. Si elle est décochée la cache prendra la demande d\'url et les variables de demande en compte quand le bloc est caché.';
$xarML_PHPBackend_entries['- Optionally share the block between users. Options are'] = '-Partage optionnalement le bloc entre les utilisateurs. Les options sont';
$xarML_PHPBackend_entries['- Caches block per user. All users see a distinct cached copy.'] = 'Bloc de cache par utilisateur. Tous les utilisateurs voient une copie de cache distincte.';
$xarML_PHPBackend_entries['- Caches block per user group. All users in the same group see the same cached copy.'] = 'Bloc de cache par groupe d\'utilisateur. Tous les utilisateurs dans le même groupe voient la même copie de cache.';
$xarML_PHPBackend_entries['- Caches one copy for all users.'] = 'Une copie de cache pour tous les utilisateurs';
$xarML_PHPBackend_entries['- The length of time before a cached block becomes stale. Expects a string indicating the length of time to cache the block in the format'] = '- La longueur de temps avant que le bloc de cahe ne soit périmé. Prévoir une chaîne indicant la longueur de temps pour le format du bloc de cache';
$xarML_PHPBackend_entries['dd:hh:mm:ss'] = 'dd:hh:mm:ss';
$xarML_PHPBackend_entries['A value of 0 means the cache only expires if the block changes as a result of updating the block.'] = 'Une valeur de 0 signifie que la cache expire seulement si le bloc change comme résultat de la mise à jour du bloc.';
$xarML_PHPBackend_entries['Administrators can configure access options for blocks and block types.'] = 'Les administrateurs peuvent configurer les options d\'accès pour les blocs et les types de bloc.';
$xarML_PHPBackend_entries['The common access options you can set per access level are as follows'] = 'Les options d\'accès communes vous pouvez configurer par niveau d\'accès comme ceci';
$xarML_PHPBackend_entries['Access Property'] = 'Propriété d\'accès';
$xarML_PHPBackend_entries['Required Group Membership'] = 'Abonnement de groupe requis';
$xarML_PHPBackend_entries['- allows access based on current role membership (optional)'] = '-permet l\'accès basé sur l\'abonnement de rôle actule (optionnel)';
$xarML_PHPBackend_entries['No Requirement'] = 'Aucun pré requis';
$xarML_PHPBackend_entries['- all users'] = '-tous les utilisateurs';
$xarML_PHPBackend_entries['Users not logged in'] = 'Utilisateurs non connectés';
$xarML_PHPBackend_entries['- all anonymous users'] = '-tous les utilisateurs anonymes';
$xarML_PHPBackend_entries['Users logged in'] = 'Utilisateurs connectés';
$xarML_PHPBackend_entries['- all logged in users, all groups'] = '-tous les utilisateurs connectés, tous les groupes';
$xarML_PHPBackend_entries['groupName'] = 'Nom du groupe';
$xarML_PHPBackend_entries['- all users in a group'] = 'tous les utilisateurs dans un groupe';
$xarML_PHPBackend_entries['Required Access Level'] = 'Niveau d\'accès requis';
$xarML_PHPBackend_entries['- used when Group Membership has No Requirement, allow access to users with this level or greater access.'] = 'utilisé quand un abonnement de groupe n\'a pas de pré-requis permet l\'accès aux utilisateurs avec ce niveau ou un niveau plus élevé d\'accès.';
$xarML_PHPBackend_entries['Behaviour on Failure'] = 'Comportement échoué';
$xarML_PHPBackend_entries['- either show a privilege error for failed access, or fail silently.'] = '-soit vous affichez une erreur de privilège pour l\'accès échoué ou échouer silencieusement.';
$xarML_PHPBackend_entries['Block Access'] = 'Accès au bloc';
$xarML_PHPBackend_entries['Administrators can configure the following options per block instance from the Access tab available when editing a block.'] = 'Les administrateus peuvent configurer les options suivantes pour chaque instance de bloc à partir de l\'onglet d\'accès disponible quand vous éditez un bloc.';
$xarML_PHPBackend_entries['Display Access'] = 'Afficher l\'accès';
$xarML_PHPBackend_entries['- controls who the block will be displayed to.'] = '-contrôle pour qui le bloc est affiché.';
$xarML_PHPBackend_entries['Modify Access'] = 'Modifier l\'accès';
$xarML_PHPBackend_entries['- controls who can modify the block type properties.'] = '- contrôle qui peut modifier les propriétés du type de bloc.';
$xarML_PHPBackend_entries['Delete Access'] = 'Supprimer l\'accès';
$xarML_PHPBackend_entries['- controls who can delete the block.'] = '- contrôle qui peut supprimer le bloc';
$xarML_PHPBackend_entries['Block Type Access'] = 'Accès au type de bloc';
$xarML_PHPBackend_entries['Administrators can configure the following options per block type when editing a block type.'] = 'Les administrateurs peuvent configurer les options suivantes par type de bloc quand vous éditez un type de bloc.';
$xarML_PHPBackend_entries['Add Access'] = 'Ajouter l\'accès';
$xarML_PHPBackend_entries['- controls who can add blocks of this type.'] = '- contrôle wui peut ajouter des blocs de ce type.';
?>