<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Dynamic Data'] = 'DynamicData';
$xarML_PHPBackend_entries['Module'] = 'Modul';
$xarML_PHPBackend_entries['Link Type'] = 'Link-Typ';
$xarML_PHPBackend_entries['From'] = 'Von';
$xarML_PHPBackend_entries['To'] = 'An';
$xarML_PHPBackend_entries['Dynamic Data Utilities'] = 'DynamicData-Utilities';
$xarML_PHPBackend_entries['ID'] = 'ID';
$xarML_PHPBackend_entries['Name'] = 'Name';
$xarML_PHPBackend_entries['Label'] = 'Label';
$xarML_PHPBackend_entries['Default'] = 'Standard';
$xarML_PHPBackend_entries['Data Source'] = 'Datenquelle';
$xarML_PHPBackend_entries['Modify Item #(1) in #(2)'] = 'Element #(1) in #(2) ändern';
$xarML_PHPBackend_entries['Input Format'] = 'Eingabeformat';
$xarML_PHPBackend_entries['New'] = 'Neu';
$xarML_PHPBackend_entries['Refresh'] = 'Erneut laden';
$xarML_PHPBackend_entries['fields or values'] = 'Felder oder Werte';
$xarML_PHPBackend_entries['View #(1)'] = '#(1) anzeigen';
$xarML_PHPBackend_entries['View'] = 'Anzeige';
$xarML_PHPBackend_entries['Please select one of the available objects'] = 'Bitte eins der verfügbaren Objekte auswählen';
$xarML_PHPBackend_entries['Preview'] = 'Vorschau';
$xarML_PHPBackend_entries['Type'] = 'Typ';
$xarML_PHPBackend_entries['Source'] = 'Quelle';
$xarML_PHPBackend_entries['Delete'] = 'Löschen';
$xarML_PHPBackend_entries['Item details'] = 'Elementdetails';
$xarML_PHPBackend_entries['Items:'] = 'Elemente:';
$xarML_PHPBackend_entries['Options'] = 'Optionen';
$xarML_PHPBackend_entries['Query'] = 'Abfragen';
$xarML_PHPBackend_entries['Specify your own layout here...'] = 'Geben Sie hier Ihr eigenes Layout an...';
$xarML_PHPBackend_entries['Overview'] = 'Überblick';
$xarML_PHPBackend_entries['Edit'] = 'Bearbeiten';
$xarML_PHPBackend_entries['Add'] = 'Hinzufügen';
$xarML_PHPBackend_entries['Property Type'] = 'Eigenschaftstyp';
$xarML_PHPBackend_entries['Object:'] = 'Objekt:';
$xarML_PHPBackend_entries['Table:'] = 'Tabelle:';
$xarML_PHPBackend_entries['Confirm Deleting This Item?'] = 'Löschen bestätigen?';
$xarML_PHPBackend_entries['Search for'] = 'Suchen nach';
$xarML_PHPBackend_entries['Search'] = 'Suchen';
$xarML_PHPBackend_entries['Add Relation'] = 'Beziehung hinzufügen';
$xarML_PHPBackend_entries['Auto allocated'] = 'Automatisch zugeteilt';
?>