<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Reload'] = 'Actualiser';
$xarML_PHPBackend_entries['Plain'] = 'Plein';
$xarML_PHPBackend_entries['Icons'] = 'Icones';
$xarML_PHPBackend_entries['Compact-A'] = 'Compact-A';
$xarML_PHPBackend_entries['Compact-B'] = 'Compact-B';
$xarML_PHPBackend_entries['All Modules'] = 'Tous les modules';
$xarML_PHPBackend_entries['All Installed'] = 'Modules installés';
$xarML_PHPBackend_entries['All Active'] = 'Modules Actifs';
$xarML_PHPBackend_entries['All Inactive'] = 'Modules Inactifs';
$xarML_PHPBackend_entries['All Upgraded'] = 'Modules mis à jour';
$xarML_PHPBackend_entries['Not Installed'] = 'Non installé';
$xarML_PHPBackend_entries['Missing (Not Installed)'] = 'Manquant (non installé)';
$xarML_PHPBackend_entries['Missing (Inactive)'] = 'Manquant (inactif)';
$xarML_PHPBackend_entries['Missing (Active)'] = 'Manquant (actif)';
$xarML_PHPBackend_entries['Missing (Upgraded)'] = 'Manquant (mis à jour)';
$xarML_PHPBackend_entries['Update (Not Installed)'] = 'A jour (non installé)';
$xarML_PHPBackend_entries['Update (Inactive)'] = 'A jour (inactif)';
$xarML_PHPBackend_entries['Update (Active)'] = 'A jour (actif)';
$xarML_PHPBackend_entries['Update (Upgraded)'] = 'A jour (mis à jour)';
$xarML_PHPBackend_entries['Name [a-z]'] = 'Nom [a-z]';
$xarML_PHPBackend_entries['Name [z-a]'] = 'Nom [z-a]';
$xarML_PHPBackend_entries['Go to administration of'] = 'Aller à l\'administration de';
$xarML_PHPBackend_entries['On/Off'] = 'On/Off';
$xarML_PHPBackend_entries['Inactive'] = 'Inactif';
$xarML_PHPBackend_entries['Active'] = 'Actif';
$xarML_PHPBackend_entries['[core module]'] = '[module du noyau]';
$xarML_PHPBackend_entries['Missing'] = 'Manquant';
$xarML_PHPBackend_entries['Error'] = 'Erreur';
$xarML_PHPBackend_entries['View Error'] = 'Voir l\'erreur';
$xarML_PHPBackend_entries['New version'] = 'Nouvelle version';
$xarML_PHPBackend_entries['Remove (Bug! in list generation)'] = 'Enlever (Bug! lors de la génération de la liste)';
?>