<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['User Registration'] = 'Benutzeranmeldung';
$xarML_PHPBackend_entries['Privacy Policy'] = 'Datenschutz';
$xarML_PHPBackend_entries['Terms of Use'] = 'Nutzungsbedingungen';
$xarML_PHPBackend_entries['Logout'] = 'Abmelden';
$xarML_PHPBackend_entries['New Account'] = 'Neues Konto';
$xarML_PHPBackend_entries['Create User Account'] = 'Benutzerkonto anlegen';
$xarML_PHPBackend_entries['Registration'] = 'Registrierung';
$xarML_PHPBackend_entries['Registration Requirements'] = 'Voraussetzungen für die Registrierung';
$xarML_PHPBackend_entries['Instructions Sent'] = 'Anleitungen wurden versandt';
$xarML_PHPBackend_entries['zero'] = 'null';
$xarML_PHPBackend_entries['one'] = 'eins';
$xarML_PHPBackend_entries['two'] = 'zwei';
$xarML_PHPBackend_entries['three'] = 'drei';
$xarML_PHPBackend_entries['four'] = 'vier';
$xarML_PHPBackend_entries['five'] = 'fünf';
$xarML_PHPBackend_entries['six'] = 'sechs';
$xarML_PHPBackend_entries['seven'] = 'sieben';
$xarML_PHPBackend_entries['eight'] = 'acht';
$xarML_PHPBackend_entries['nine'] = 'neun';
$xarML_PHPBackend_entries['ten'] = 'zehn';
$xarML_PHPBackend_entries['eleven'] = 'elf';
$xarML_PHPBackend_entries['twelve'] = 'zwölf';
$xarML_PHPBackend_entries['thirteen'] = 'dreizehn';
$xarML_PHPBackend_entries['fourteen'] = 'vierzehn';
$xarML_PHPBackend_entries['fifteen'] = 'fünfzehn';
$xarML_PHPBackend_entries['sixteen'] = 'sechszehn';
$xarML_PHPBackend_entries['seventeen'] = 'siebzehn';
$xarML_PHPBackend_entries['eighteen'] = 'achtzehn';
$xarML_PHPBackend_entries['nineteen'] = 'neunzehn';
$xarML_PHPBackend_entries['twenty'] = 'zwanzig';
$xarML_PHPBackend_entries['twenty-one'] = 'einundzwanzig';
$xarML_PHPBackend_entries['Please review the above information and check it for correctness. Click Create Account to continue.'] = 'Bitte prüfen Sie die obigen Daten auf Richtigkeit. Klicken Sie  auf "Konto erstellen" um weiterzufahren.';
$xarML_PHPBackend_entries['Overview'] = 'Überblick';
$xarML_PHPBackend_entries['Status:'] = 'Status:';
$xarML_PHPBackend_entries['User ID:'] = 'Benutzername:';
$xarML_PHPBackend_entries['Modify Configuration'] = 'Konfiguration ändern';
$xarML_PHPBackend_entries['Username:'] = 'Benutzername';
?>