<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['Site Contact'] = 'Site Contact';
$xarML_PHPBackend_entries['at'] = 'um';
$xarML_PHPBackend_entries['Invalid #(1) for #(2) function #(3)() in module #(4)'] = 'Ungültig: #(1) für #(2) Funktion #(3)() in Modul #(4)';
$xarML_PHPBackend_entries['The form requested is not available'] = 'Das gewünschte Formular steht nicht zur Verfügung';
$xarML_PHPBackend_entries['Submit'] = 'Losschicken';
$xarML_PHPBackend_entries['Form ID'] = 'Formular-ID';
$xarML_PHPBackend_entries['Form Name'] = 'Formularname';
$xarML_PHPBackend_entries['Name'] = 'Name';
$xarML_PHPBackend_entries['Email'] = 'E-Mail';
$xarML_PHPBackend_entries['Subject'] = 'Betreff';
$xarML_PHPBackend_entries['Organization'] = 'Organisation: / Verein';
$xarML_PHPBackend_entries['SiteContact Administration'] = 'Administration des SiteContact-Moduls';
$xarML_PHPBackend_entries['Manage Contact Forms'] = 'Kontaktformulare verwalten';
$xarML_PHPBackend_entries['Review Responses'] = 'Antworten durchsehen';
$xarML_PHPBackend_entries['Contact Form'] = 'Kontaktformular';
$xarML_PHPBackend_entries['You submitted the following information:'] = 'Sie haben die folgende Information eingereicht:';
$xarML_PHPBackend_entries['Name:'] = 'Name:';
$xarML_PHPBackend_entries['Email:'] = 'E-Mail:';
$xarML_PHPBackend_entries['Subject:'] = 'Betreff:';
$xarML_PHPBackend_entries['Separate emails by colons (;) or optionally add a name for each email by separating email and name by a comma eg'] = 'Trennen Sie E-Mails durch Semikolons (;) oder fügen Sie optional zu jeder E-Mail-Adresse einen Namen hinzu, E-Mail und Namen dabei durch ein Komma getrennt';
$xarML_PHPBackend_entries['email1@somedomain.com,SomeName;'] = 'emailadresse1@ihredomain.com,IhrName;';
$xarML_PHPBackend_entries['Copy email to you?'] = 'Kopie der Email an mich?';
$xarML_PHPBackend_entries['Permit saving of your form response?'] = 'Eingegbene Formulare speichern?';
$xarML_PHPBackend_entries['User information:'] = 'Benutzerinfo:';
$xarML_PHPBackend_entries['Site Contact Administration'] = 'Administration des Moduls SiteContact';
$xarML_PHPBackend_entries['Custom page title:'] = 'Seitentitel:';
$xarML_PHPBackend_entries['Your custom text:'] = 'Ihr Einleitungstext:';
$xarML_PHPBackend_entries['Confirm Page Text:'] = 'Text der Bestätigungsmail';
$xarML_PHPBackend_entries['Allow CC Recipient list?'] = 'CC-Empfängerliste zulassen?';
$xarML_PHPBackend_entries['Allow BCC Recipient list?'] = 'BCC-Empfängerliste zulassen?';
$xarML_PHPBackend_entries['Save form responses to the database?'] = 'Formularantworten in der Datenbank sichern?';
$xarML_PHPBackend_entries['Terms link URL :'] = 'Link zu den Nutzungsbedingungen:';
$xarML_PHPBackend_entries['Options for subject with optional alternative email address:'] = 'Optionen für den Betreff mit optional alternativen Emailadressen:';
$xarML_PHPBackend_entries['Each line above should be entered with the semicolon and comma:'] = 'Jede Zeile sollte mit Semikolon und Komma eingegeben werden:';
$xarML_PHPBackend_entries['subject;optional-email,'] = 'Betreff;optionale Emailadresse,';
$xarML_PHPBackend_entries['The optional email and semicolon can be omitted but must have comma to separate each line.'] = 'Die optionale Emailadresse sowie das Semikolon können entfallen, allerdings muss am Ende <strong>jeder</strong> Zeile ein Komma gesetzt werden (um die Zeilen voneinander zu trennen).';
$xarML_PHPBackend_entries['Allow anonymous users to also request a copy?'] = 'Anonyme Benutzer können eine Kopie verlangen?';
$xarML_PHPBackend_entries['NOTE: Please ensure you understand the potential problems of allowing
copy to sender option (spammer use) if you have open access on your website to this specific form.'] = 'HINWEIS: Sie sollten sich über die Problematik im Klaren sein, wenn Sie die Option "Kopie an Absender" erlauben (Spammer-Mißbrauch!) für den Fall, dass Sie offenen Zugang zu diesem spezifischen Formular zulassen.';
$xarML_PHPBackend_entries['Use HTML Email?'] = 'HTML in der Email verwenden?';
$xarML_PHPBackend_entries['Default emailed note to user (in template as ##$notetouser##):'] = 'Standardmäßiger Emailhinweis an den Nutzer:';
$xarML_PHPBackend_entries['You can use the following variables in your email:'] = 'Sie können folgende Variablen in Ihrer Email verwenden:';
$xarML_PHPBackend_entries['User email'] = 'Benutzeremail';
$xarML_PHPBackend_entries['User name'] = 'Benutzername';
$xarML_PHPBackend_entries['Subject from drop down list'] = 'Betreff von der Auswahlliste';
$xarML_PHPBackend_entries['Create Form'] = 'Formular anlegen';
$xarML_PHPBackend_entries['NOTE: Please ensure you understand the potential problems of allowing
muliple emailings (spammer use) if you have open access on your website to this form.'] = 'HINWEIS: Wenn sie mehrfaches E-Mailen erlauben, sollten Sie sich sicher sein, die damit zusammenhängenden Probleme zu kennen, wenn Sie auf Ihrer Website offenen Zugang zu diesem Formular ermöglichen.';
$xarML_PHPBackend_entries['Delete'] = 'Löschen';
$xarML_PHPBackend_entries['Options'] = 'Optionen';
$xarML_PHPBackend_entries['Edit'] = 'Bearbeiten';
$xarML_PHPBackend_entries['Overview'] = 'Überblick';
$xarML_PHPBackend_entries['Submitted By:'] = 'Eingereicht von:';
$xarML_PHPBackend_entries['Sitecontact Administration'] = 'Sitecontact-Administration';
$xarML_PHPBackend_entries['Sender:'] = 'IP des Absender:';
$xarML_PHPBackend_entries['Referer:'] = 'Referer:';
$xarML_PHPBackend_entries['Response ID'] = 'Antwort-ID';
$xarML_PHPBackend_entries['Common Administration menu'] = 'Allgemeines Admin-Menü';
?>