<?php
global $xarML_PHPBackend_entries;
global $xarML_PHPBackend_keyEntries;
$xarML_PHPBackend_entries['All'] = 'Tous';
$xarML_PHPBackend_entries['Add Files'] = 'Ajouter des fichiers';
$xarML_PHPBackend_entries['Refresh'] = 'Rafraîchir';
$xarML_PHPBackend_entries['Unable to purge rejected files!'] = 'Impossible de purger les fichiers rejetés !';
$xarML_PHPBackend_entries['Error Found: #(1)'] = 'Erreur trouvé : #(1)';
$xarML_PHPBackend_entries['Uploads Module Overview'] = 'Vue d\'ensemble du module de téléchargement';
$xarML_PHPBackend_entries['Overview'] = 'Vue d\'ensemble';
$xarML_PHPBackend_entries['View Files'] = 'Voir les fichiers';
$xarML_PHPBackend_entries['File Name'] = 'Nom de fichier';
$xarML_PHPBackend_entries['Uploads Administration'] = 'Administration des téléchargements';
$xarML_PHPBackend_entries['File'] = 'Fichier';
$xarML_PHPBackend_entries['Import'] = 'Importer';
$xarML_PHPBackend_entries['File Administration'] = 'Administration du fichier';
$xarML_PHPBackend_entries['Admin'] = 'Administration';
$xarML_PHPBackend_entries['MIME Type'] = 'Type MIME';
$xarML_PHPBackend_entries['MIME SubType'] = 'Sous type MIME';
$xarML_PHPBackend_entries['Delete'] = 'Effacer';
$xarML_PHPBackend_entries['Purge Rejected Files'] = 'Purger les fichiers rejetés';
$xarML_PHPBackend_entries['Select'] = 'Sélectionner';
$xarML_PHPBackend_entries['Uploaded By'] = 'Chargé par';
$xarML_PHPBackend_entries['You do not have the necessary permissions for this object.'] = 'Vous n\'avez pas les permissions nécessaires pour cet objet.';
$xarML_PHPBackend_entries['Missing parameter [#(1)] for function [#(2)] in module [#(3)]'] = 'Paramètre [#(1)] manquant pour la fonction [#(2)] dans le module [#(3)]';
$xarML_PHPBackend_entries['Download file: #(1)'] = 'Télécharger le fichier #(1)';
$xarML_PHPBackend_entries['Rejected'] = 'Rejeté';
$xarML_PHPBackend_entries['Approved'] = 'Approuvé';
$xarML_PHPBackend_entries['Submitted'] = 'Soumis';
$xarML_PHPBackend_entries['Unknown!'] = 'Inconnu !';
$xarML_PHPBackend_entries['Missing parameter [#(1)] for function [(#(2)] in module [#(3)]'] = 'Paramètre [#(1)] manquant pour la fonction [#(2)] dans le module [#(3)]';
$xarML_PHPBackend_entries['Unable to connect to host [#(1):#(2)] to retrieve file [#(3)]'] = 'Impossible de se connecter au serveur  [#(1):#(2)]pour récupérer le fichier [#(3)]';
$xarML_PHPBackend_entries['Unable to open temp file to store remote host [#(1):#(2)] file [#(3)]'] = 'Impossible d\'ouvrir le fichier temporaire pour stocker le fichier [#(3)] sur le serveur distant [#(1):#(2)]';
$xarML_PHPBackend_entries['Unable to write to temp file!'] = 'Impossible d\'écrire dans le fichier temporaire !';
$xarML_PHPBackend_entries['The file was only partially uploaded.'] = 'Le fichier a été seulement chargé partiellement.';
$xarML_PHPBackend_entries['No file was uploaded..'] = 'Aucun fichier n\'a été chargé...';
$xarML_PHPBackend_entries['Possible attempted malicious file upload.'] = 'Essai possible de chargement d\'un fichier malveillant.';
$xarML_PHPBackend_entries['Save Location<br />DB / FS'] = 'Méthode de stockage<br /> Base de données / Système de fichiers';
$xarML_PHPBackend_entries['Action'] = 'Action';
?>